### ISSUE TITLE
Kernel of Xiaomi mix(22/5/2018,Oreo for miui)does't work

### ISSUE THREAD

**Issue by jku1995** [JonasCardoso/android_kernel_xiaomi_msm8996#116]
Yesterday,I flash this kernel,and when I reboot my phone,it interrupt and my phone's screen show "MI"logo so long time so that i have to flash MIUI offical package again to save my phone ,my MIUI version is MIUI 10 Oreo-8.6.14，I wanna a Kernel to control Sdm 821(msm8996 pro)myself，Are you going to update it?

**Comment by JonasCardoso** [comment]
Dont have kernel for miui-o working yet
