### ISSUE TITLE
WiFi MAC address changed

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [JonasCardoso/android_kernel_xiaomi_msm8996#119]
MIUI Nougat latest build for Natrium got Wifi MAC changed to 00:03:7F:C2:00:43 but working properly.

Tried the Google & Linaro.

**Comment by JonasCardoso** [comment]
without wifi drops?

**Comment by Crescendo-BLYAT** [comment]
yes, without any issue... only the mac is changed.

the wlan.mac in /persist/wlan_bt is intact and contaning my real mac...

do you need it?

**Comment by Crescendo-BLYAT** [comment]
more info: the file that xiaomi used to put the wlan mac info isn't used anymore.

It symlinked to nothing.

file: /etc/firmware/wlan/qca_cld/wlan_mac.bin

symlinked to: /persist/wlan_mac.bin (non-existent even in my other untouched Natrium phone)

the real MAC is contained in /persist/wlan_bt/wlan.mac

**Comment by JonasCardoso** [comment]
i will remove wlan.ko in zip, kernel i will use module default in ROM

**Comment by JonasCardoso** [comment]
or no

**Comment by JonasCardoso** [comment]
I'll keep wlan driver, less problems

**Comment by Crescendo-BLYAT** [comment]
I tried to use the wlan.ko from the ROM but the kernel failed to activate the wifi...

**Comment by JonasCardoso** [comment]
Yes, some ROMs work and other no, i will keep driver in zip

**Comment by Crescendo-BLYAT** [comment]
yep as MIUI builds can vary greatly between versions, I'm aware of this as I used to use their Beta ROM.

dunno why xiaomi did that...

hope you can fix the problem with mac address coz I can't flash it to my other phone (it will cause problem with duplicate MAC on same wifi)...

**Comment by Crescendo-BLYAT** [comment]
do you find the cause for MAC change?

**Comment by JonasCardoso** [comment]
nop yet

**Comment by Crescendo-BLYAT** [comment]
I tried to copy & rename the file **wlan.mac** to **wlan_mac.bin** in **/persist** so the symlinked-to-nothing file **/etc/firmware/wlan/qca_cld/wlan_mac.bin** actually linked to real file.

Aaaand, the MAC still the generic ones... lol

**Comment by JonasCardoso** [comment]
Use last wlan in builds before update

**Comment by Crescendo-BLYAT** [comment]
wait, what wlan in what builds?
what update? 
sorry, I don't understand.

I'm using MIUI-N 26082018 Google now. 

First time using your kernel was the 20082018 Google then Linaro then back to Google, it already changed the wifi MAC.

Updated to 24082018 then 26082018 (MAC still generic).

**Comment by JonasCardoso** [comment]
wlan before changed your mac (20/08)

**Comment by Crescendo-BLYAT** [comment]
so, flash 20082018 build and see the MAC? 

FYI 20-08-2018 changed my MAC.

I'll flash it now & report back...

**Comment by JonasCardoso** [comment]
or get wlan driver inside zip and change in most recent zip kernel

**Comment by Crescendo-BLYAT** [comment]
wait, sorry I'm really confused...

get the older kernel prior 20/08, extract the wlan.ko and put it into the newest kernel?

**Comment by JonasCardoso** [comment]
yep

**Comment by Crescendo-BLYAT** [comment]
nope, no dice...

it failed to turn on wifi, and the MAC become 02:00:00:00:00:00 

I'll flash the 08/08 Google kernel now...

**Comment by Crescendo-BLYAT** [comment]
nope, still the same as 20/08 or 24/08 or 26/08...

generic MAC but working OK

**Comment by liudaxia1478** [comment]
你好，我在我的mix设备上刷入你的内核，wlan和相机无法工作，可以解决吗，期待你的回答

**Comment by CrescendoFang** [comment]
@JonasCardoso any info on this?

**Comment by CrescendoFang** [comment]
the devs stopped working on this kernel....

**Comment by Crescendo-BLYAT** [comment]
@JonasCardoso any info on this?

**Comment by Mandi-Sa** [comment]
same problem with miui-o

**Comment by Crescendo-BLYAT** [comment]
@Angelina-ACE @JonasCardoso 

is it fixed on latest build of miui-o?

**Comment by Crescendo-BLYAT** [comment]
@JonasCardoso  any news on this bug?
 I really wanna use this kernel....

**Comment by Crescendo-BLYAT** [comment]
not relevant to me anymore, I'm switching to Syberia OS with this EAS-P kernel.. Wifi is OK
