### ISSUE TITLE
Qualcomm Quick Charge 3.0

### ISSUE THREAD

**Issue by dnullptr** [JonasCardoso/android_kernel_xiaomi_msm8996#120]
Hello Jonas. 
Best kernel ever made to gemini. Period.
I've been testing most of them including Miui , HMP and EAS . And man.. even Pie support!
I wonder why no one had ever mentioned that , but Quick Charge 3.0 won't be recognized , giving a +17~20 minutes in any charging cycle.
Moreover, with voltage detector it didn't of course trigger the 9V charging resulting in 5V 2A fast charge but not 9V.

You are the best , keep up the flawlessly excellent work.
Danik.

**Comment by dnullptr** [comment]
For TL;DR - 
- 9V QC3.0 not working on Oreo MIUI (maybe others too..)

**Comment by JonasCardoso** [comment]
i noticed this, i already wrote this down to try and fix it soon

**Comment by JonasCardoso** [comment]
i sent two test in telegram group, https://t.me/joinchat/BCxlgEh309Im9gdVceE-cA, test and send for me the results

**Comment by dnullptr** [comment]
Hey Jonas, tried flashing the QC test for Miui-O.
(3/9) for some reason it wouldn't even boot (freezes at boot logo and reboots).

Anyways, thank you for your contribution it is not obvious! :)

**Comment by dnullptr** [comment]
**Temporary Workaround**
For Oreo MIUI which is not utilizing QC3.0 in  Floppy Kernel.

1.Flash Floppy and Root with Magisk 17+.
2.Download FastChargingMod CVC module from Magisk.
3.Install , Reboot.
4.In Terminal type : su , then run.sh
5. Press 3 to run mod , then press 1 for 3000mA.
6.Reboot.

*This module is for Revolt Kernel (which our devices don't have though it will apply many of the parameters needed for 3000mA charging. And it is enough to work :)

**This is not a fix for Oreo MIUI quick charge in Floppy Kernel , but it will utilize 3 Amperes instead of 2.0/2.4A only in 5V mode , which really gets face to face with quick charge 3.0's 9V/1.67A. (~15W anyways)
Here it goes : https://imgur.com/a/iMW0Wfx.

Enjoy it for now.

**Comment by JonasCardoso** [comment]
fixed
