### ISSUE TITLE
Screen Brightness

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [JonasCardoso/android_kernel_xiaomi_msm8996#121]
Unable to remember screen brightness for certain lighting condition like default MIUI does.q

**Comment by JonasCardoso** [comment]
try disable  backlight dimmer option

**Comment by Crescendo-BLYAT** [comment]
already but it reverted my preset brightness value to default upon reboot (as Kernel Adiutor needs time to apply)...

maybe disable it as default?

**Comment by JonasCardoso** [comment]
you can add code here to disable, is a possible way or compiling the kernel with it disabled by default 
https://github.com/JonasCardoso/android_kernel_xiaomi_msm8996/blob/hmp-o/zip-creator/base/ramdisk/init.floppy.rc

**Comment by Crescendo-BLYAT** [comment]
I'll try to compile with it disabled as default... thanks 😊

**Comment by JonasCardoso** [comment]
https://github.com/JonasCardoso/android_kernel_xiaomi_msm8996/commit/bec57ec2ce0287070c7f9b4c68d9745a280a6c89#diff-e3cf79ab8846fdd183958146bd82ea50R87
