### ISSUE TITLE
Thermal control MIUI-N

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [JonasCardoso/android_kernel_xiaomi_msm8996#122]
I noticed that the thermal control of this kernel is unable to override the Xiaomi's.
I didn't change the value, just simply enabled the intellithermal & core control.

Xiaomi's tried to cap the temp to 40C, while the kernel throttle at 90C & temp limit 80C (default).

The reality was the phone throttle everything down and I can only get 43C max.

--------------

Then I deleted the Xiaomi's **thermal-engine-8996.conf** file, thus freeing the phone from Xiaomi's thermal control.
Reboot.
Intellithermal & core control enabled, CPU throttle value 70C, temp limit 60C.

Gaming time now, the temp soar as high as 90C and stays there, no throttling.
It doesn't even honor the kernel thermal settings.

--------------

FYI, xiaomi curiously got 3 encrypted thermal-engine-8996 file:
thermal-engine-8996.conf
thermal-engine-8996-map.conf
thermal-engine-8996-high.conf

but the only file that really affect the phone was **thermal-engine-8996.conf**

**Comment by Crescendo-BLYAT** [comment]
latest ver seems working now...

**Comment by Crescendo-BLYAT** [comment]
seems the thermal settings got ignored if I use ANY of the CPU hotplug except the default....

**Comment by CrescendoFang** [comment]
the devs stopped working on this kernel....

**Comment by Crescendo-BLYAT** [comment]
the devs stopped working on this kernel....

**Comment by CrescendoFang** [comment]
the devs stopped working on this kernel....
