### ISSUE TITLE
Camera issue

### ISSUE THREAD

**Issue by kartun83** [JonasCardoso/android_kernel_xiaomi_msm8996#123]
Hello.
I've installed PIE on mi5s using [this guide](https://forum.xda-developers.com/mi-5s/how-to/treble-install-android-pie-t3826089) 
With your latest kernel for P camera isn't working, but it works with [BG kernel](https://forum.xda-developers.com/mi-5s/development/kernel-bg345-kernel-capricorn-t3756847/post76764853#post76764853).
Could you please take a look?

**Comment by JonasCardoso** [comment]
Treble's vendor is outdated, mi5 have same problem
