### ISSUE TITLE
kcal settings resetting after screen lock on miui oreo

### ISSUE THREAD

**Issue by ghost** [JonasCardoso/android_kernel_xiaomi_msm8996#126]
kcal settings disabling after screen lock on miui oreo mi5s. the values have to change with every lock & unlock.
i dont know its related with kernel or miui rom.

**Comment by JonasCardoso** [comment]
Miui ROM feature

**Comment by ghost** [comment]
> Miui ROM feature

so, kcal is useless on miui-o. is there any possible solution?

**Comment by JonasCardoso** [comment]
> > Miui ROM feature
> 
> so, kcal is useless on miui-o. is there any possible solution?

I tried to fix it once, but to no avail

**Comment by xCorbe** [comment]
Bro please fix kcal support for MIUI 10 Oreo
