### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by chhapil** [JonasCardoso/android_kernel_xiaomi_msm8996#63]
i reckon you already solved the segmentation fault error getting thrown from cypto backage when using gcc 7 or ubertc 8.
how did u fixed it?

**Comment by JonasCardoso** [comment]
What error exactly are you referring to? I'm not sure if I fixed this

**Comment by chhapil** [comment]
never mind, i removed the graphite flags from makefile, that solved it
