### ISSUE TITLE
Worse performance after 1501 builds

### ISSUE THREAD

**Issue by kartun83** [JonasCardoso/android_kernel_xiaomi_msm8996#80]
I'm running kernel 1501 and it's ok. Tried to use later builds, but it is extremely laggy.
On mi5s, lineage 8.1, latest

**Comment by JonasCardoso** [comment]
You have links for the buids? I want to check something out on MI5

**Comment by kartun83** [comment]
@JonasCardoso : https://androidfilehost.com/?w=files&flid=234416
I'm on mi5s, not legacy mi5, if it maters.

**Comment by JonasCardoso** [comment]
Ok, i will take a look
