### ISSUE TITLE
The Oreo version of the kernel has a very serious lag

### ISSUE THREAD

**Issue by CrazyDoge666** [JonasCardoso/android_kernel_xiaomi_msm8996#82]
My phone is MI5's latest AEX
And when I use this kernel for a while, the screen will flicker at about 1/3, but I can guarantee that ROM and the kernel are clean.

**Comment by CrazyDoge666** [comment]
Hello, this kernel has some problems on my mobile phone
The core of the Oreo version has an unusually serious viscosity
And when typing, the input method will be more frequent when the game is flashing.
I hope you can fix it, thank you.

**Comment by JonasCardoso** [comment]
Kernel  oreo is unstable yet

**Comment by JonasCardoso** [comment]
Use nougat
